import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Todo-list App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, // will be a page or nested layout
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div>Header</div>
        <main>{children}</main>
        <div>Footer</div>
      </body>
    </html>
  );
}
